apiVersion: v1
kind: Service
metadata:
  name: tenants-dashboard
  labels:
    app: tenants-dashboard
spec:
  type: ClusterIP
  ports:
  - port: 5173
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: tenants-dashboard
